# Generated by Django 5.2.7 on 2025-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='photos/man1.webp', null=True, upload_to='profile_pics/'),
        ),
    ]
