# Generated by Django 5.2.7 on 2025-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_rename_ordered_at_order_created_at_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
