# Generated by Django 5.2.7 on 2025-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_tweet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
